[project]
name = "g0vse"
version = "0.1.0"
description = "Making the Swedish government's website (regeringen.se) accessible as open data."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cloverlabs-camoufox[geoip]>=0.6.0",
    "fake-useragent>=2.2.0",
    "html-to-markdown>=2.24.5",
    "selectolax>=0.4.6",
    "tqdm>=4.67.3"
]

[tool.setuptools.packages.find]
include = ["services*"]
exclude = ["frontend*", "data*"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
