# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["data"]
  workflow_run:
    workflows: ["Download new pages from regeringen.se", "Build the frontend"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout data branch
        uses: actions/checkout@v4
        with:
          ref: 'data'
      - name: Checkout frontend branch
        uses: actions/checkout@v4
        with:
          ref: 'frontend'
          path: 'frontend'
      - name: Move frontend contents to root
        run: |
          mv frontend/* .
          rm -rf frontend
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
